param(
  [string]$Root = ".",
  [string]$OutputPath = "reports/skill-inventory.md"
)

$ErrorActionPreference = "Stop"
$rootAbs = (Resolve-Path -LiteralPath $Root).Path

function Get-FrontmatterValue {
  param(
    [string[]]$Lines,
    [string]$Key
  )

  foreach ($line in $Lines) {
    if ($line -match ("^{0}:\s*(.+)$" -f [regex]::Escape($Key))) {
      return $Matches[1].Trim()
    }
  }

  return ""
}

function Get-AgentDisplayName {
  param([string]$AgentPath)

  if (-not (Test-Path -LiteralPath $AgentPath -PathType Leaf)) {
    return ""
  }

  $lines = Get-Content -LiteralPath $AgentPath
  foreach ($line in $lines) {
    if ($line -match '^\s*display_name:\s*"(.+)"\s*$') {
      return $Matches[1].Trim()
    }
  }

  return ""
}

$skills = Get-ChildItem -Path $rootAbs -Recurse -File -Filter SKILL.md |
  Sort-Object FullName |
  ForEach-Object {
    $skillPath = $_.FullName
    $relPath = $skillPath.Substring($rootAbs.Length + 1).Replace('\', '/')
    $lines = Get-Content -LiteralPath $skillPath
    $name = Get-FrontmatterValue -Lines $lines -Key "name"
    $skillDir = Split-Path $skillPath -Parent
    $agentPath = Join-Path $skillDir "agents/openai.yaml"
    $displayName = Get-AgentDisplayName -AgentPath $agentPath
    $area = if ($relPath -eq "SKILL.md") { "root" } else { ($relPath.Split('/')[0]) }

    [pscustomobject]@{
      Path = $relPath
      SkillName = $name
      DisplayName = $displayName
      Area = $area
      HasMetadata = (Test-Path -LiteralPath $agentPath -PathType Leaf)
    }
  }

$totalSkills = @($skills).Count
$metadataCount = @($skills | Where-Object { $_.HasMetadata }).Count
$areaSummary = $skills |
  Group-Object Area |
  Sort-Object Name |
  ForEach-Object {
    [pscustomobject]@{
      Area = $_.Name
      Skills = $_.Count
      MetadataCount = @($_.Group | Where-Object { $_.HasMetadata }).Count
    }
  }

$reportLines = New-Object System.Collections.Generic.List[string]
$null = $reportLines.Add("# Skill Inventory")
$null = $reportLines.Add("")
$null = $reportLines.Add("This report is generated by `powershell -NoProfile -File .\scripts\generate-skill-inventory.ps1`.")
$null = $reportLines.Add("")
$null = $reportLines.Add("## Summary")
$null = $reportLines.Add("")
$null = $reportLines.Add(('- Total skills: `{0}`' -f $totalSkills))
$null = $reportLines.Add(('- Skills with `agents/openai.yaml`: `{0}/{1}`' -f $metadataCount, $totalSkills))
$null = $reportLines.Add("")
$null = $reportLines.Add("## Coverage By Area")
$null = $reportLines.Add("")
$null = $reportLines.Add("| Area | Skills | Metadata Coverage |")
$null = $reportLines.Add("|---|---:|---:|")
foreach ($row in $areaSummary) {
  $null = $reportLines.Add(("| `{0}` | {1} | {2}/{1} |" -f $row.Area, $row.Skills, $row.MetadataCount))
}
$null = $reportLines.Add("")
$null = $reportLines.Add("## Skill Table")
$null = $reportLines.Add("")
$null = $reportLines.Add("| Path | Skill Name | Display Name | Area | Metadata |")
$null = $reportLines.Add("|---|---|---|---|---|")
foreach ($skill in $skills) {
  $display = if ([string]::IsNullOrWhiteSpace($skill.DisplayName)) { "-" } else { $skill.DisplayName }
  $metadata = if ($skill.HasMetadata) { "yes" } else { "no" }
  $null = $reportLines.Add(("| `{0}` | `{1}` | {2} | `{3}` | {4} |" -f $skill.Path, $skill.SkillName, $display, $skill.Area, $metadata))
}

$resolvedOutput = if ([System.IO.Path]::IsPathRooted($OutputPath)) {
  $OutputPath
} else {
  Join-Path $rootAbs $OutputPath
}
$outputDir = Split-Path -Parent $resolvedOutput
New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
Set-Content -LiteralPath $resolvedOutput -Value $reportLines -Encoding UTF8

Write-Host ("generate-skill-inventory: wrote {0}" -f $resolvedOutput)
